service: serverless-sqs-lambda

provider:
  name: aws
  runtime: nodejs18.x  # Updated to Node.js 18.x
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sqs:SendMessage
      Resource:
        - Fn::GetAtt:
            - MessageQueue
            - Arn

functions:
  sendToSQS:
    handler: handler.sendMessage
    environment:
      SQS_QUEUE_URL:
        Ref: MessageQueue
    events:
      - http:
          path: send
          method: post

resources:
  Resources:
    MessageQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: MyQueue

  Outputs:
    SQSQueueUrl:
      Value:
        Ref: MessageQueue
